#!/bin/tcsh

#/usr/local/bin/matlab -nojvm -nodisplay < run_timestepper.m >> logts

rm -f newicsignalout
echo start > newicsignalin
while (! -e newicsignalout)
  sleep 3
end
rm -f newicsignalin
echo done
