#!/bin/tcsh

#/usr/local/bin/matlab -nojvm -nodisplay < run_timestepper.m >> logts

rm -f newpcsignalout
echo start > newpcsignalin
while (! -e newpcsignalout)
  sleep 3
end
rm -f newpcsignalin newpcsignalout
echo done
