#!/bin/tcsh

#/usr/local/bin/matlab -nojvm -nodisplay < run_timestepper.m >> logts

rm -f newjacicsignalout
echo start > newjacicsignalin
while (! -e newjacicsignalout)
  sleep 3
end
rm -f newjacicsignalin
echo done
