#!/bin/tcsh
#
# LSF batch script to run an MPI application
#
#BSUB -P COSC0001            # project code
#BSUB -W 12:00               # wall-clock time (hrs:mins)
#BSUB -n 256                 # number of tasks in job         
#BSUB -R "span[ptile=16]"    # run 16 MPI tasks per node
#BSUB -J uvok                # job name
#BSUB -o uvok.%J.out         # output file name in which %J is replaced by the job ID
#BSUB -e uvok.%J.err         # error file name in which %J is replaced by the job ID
#BSUB -q regular             # queue

module load intel
module load mkl
module load impi

mpirun.lsf ./tmmuvok \
  -numtracers 10 \
  -i dicini.petsc,c14ini.petsc,alkini.petsc,o2ini.petsc,po4ini.petsc,phytini.petsc,zoopini.petsc,detrini.petsc,no3ini.petsc,diazini.petsc \
  -me Ae \
  -mi Ai \
  -t0 0.0 -iter0 0 \
  -deltat_clock 0.0009132420091324 \
  -max_steps 5475000 \
  -write_steps 547500 \
  -o dic.petsc,c14.petsc,alk.petsc,o2.petsc,po4.petsc,phyt.petsc,zoop.petsc,detr.petsc,no3.petsc,diaz.petsc \
  -external_forcing \
  -use_profiles \
  -biogeochem_deltat 28800.0 \
  -days_per_year 365.0 \
  -periodic_matrix \
  -matrix_cycle_period 1.0 -matrix_num_per_period 12 -matrix_periodic_times_file periodic_times_365d.bin \
  -periodic_biogeochem_forcing \
  -periodic_biogeochem_cycle_period 1.0 -periodic_biogeochem_num_per_period 12 -periodic_biogeochem_periodic_times_file periodic_times_365d.bin \
  -time_avg -avg_start_time_step 5473906 -avg_time_steps 93,84,93,90,93,90,93,93,90,93,90,93 \
  -avg_files dicmm.petsc,c14mm.petsc,alkmm.petsc,o2mm.petsc,po4mm.petsc,phytmm.petsc,zoopmm.petsc,detrmm.petsc,no3mm.petsc,diazmm.petsc \
  -calc_diagnostics -diag_start_time_step 5473906 -diag_time_steps 93,84,93,90,93,90,93,93,90,93,90,93 \
  > log

# driver options:
#  I/O:
#   -pickup_out pickup.petsc \
#   -time_file output_time.txt \
#  circulation-specific options:
#   add this option for configurations in which the forcing is rescaled because of a time-varying free surface:
#    -rescale_forcing_file Rfs \
# model-specific options:
