#!/bin/tcsh
#
# LSF batch script to run an MPI application
#
#BSUB -P COSC0001            # project code
#BSUB -W 12:00               # wall-clock time (hrs:mins)
#BSUB -n 320                 # number of tasks in job         
#BSUB -R "span[ptile=16]"    # run 16 MPI tasks per node
#BSUB -J ocmip               # job name
#BSUB -o ocmip.%J.out        # output file name in which %J is replaced by the job ID
#BSUB -e ocmip.%J.err        # error file name in which %J is replaced by the job ID
#BSUB -q regular             # queue

module load intel
module load mkl
module load impi

mpirun.lsf ./tmmocmipabiolandatm \
   -numtracers 2 \
   -i dicini.petsc,dic14ini.petsc \
   -me Ae \
   -mi Ai \
   -t0 0.0 -iter0 0 \
   -deltat_clock 0.0009259259259259 \
   -max_steps 1080000 \
   -write_steps 540000 \
   -o dic_with_prescribed_pco2_core_0p24_spinup.petsc,dic14_with_prescribed_pco2_core_0p24_spinup.petsc \
   -pickup_out pickup_dic_dic14_with_prescribed_pco2_core_0p24_spinup.petsc \
   -time_file output_time_dic_dic14_with_prescribed_pco2_core_0p24_spinup.txt \
   -external_forcing \
   -use_profiles \
   -biogeochem_deltat 28800.0 \
   -periodic_matrix -matrix_cycle_period 1.0 \
   -matrix_cycle_step 0.0833333333333333 \
   -periodic_biogeochem_forcing \
   -periodic_biogeochem_cycle_period 1.0 \
   -periodic_biogeochem_cycle_step 0.08333333333333 \
   -use_winds -piston_velocity 0.24 -periodic_winds_cycle_period 1.0 -periodic_winds_cycle_step 0.0006849315068493151 \
   -pco2_atm 277.62 \
   -rescale_forcing_file Rfs \
   > log0
