#!/bin/bash               
#$ -V                     # Inherit the submission environment
#$ -cwd                   # Start job in  submission directory
#$ -N BCimp               # Job Name
#$ -j y                   # combine stderr & stdout into stdout    
#$ -o $JOB_NAME.o$JOB_ID  # Name of the output file (eg. myMPI.oJobID)
#$ -pe 16way 32           # Requests 16 cores/node, 32 cores total
#$ -q normal              # Queue name
#$ -l h_rt=24:00:00       # Run time (hh:mm:ss) - 24 hours
## -M spk@ldeo.columbia.edu      # Email notification address (UNCOMMENT)
## -m be                  # Email at Begin/End of job  (UNCOMMENT)
set -x                   #{echo cmds, use "set echo" in csh}

#export MY_NSLOTS=60

ibrun ./directimplicitpc -i v.petsc -o w.petsc -signalfiles newpcsignalin,newpcsignalout -signalwaittime 15 -ksp_rtol 1.e-12 -ksp_monitor -use_mumps -nmax 1000 > logpc
