#!/bin/tcsh
#
# LSF batch script to run an MPI application
#
#BSUB -P UCLB0003            # project code
#BSUB -W 07:00               # wall-clock time (hrs:mins)
#BSUB -n 96                  # number of tasks in job         
#BSUB -R "span[ptile=16]"    # run 16 MPI tasks per node
#BSUB -J mobi               # job name
#BSUB -o mobi.%J.out        # output file name in which %J is replaced by the job ID
#BSUB -e mobi.%J.err        # error file name in which %J is replaced by the job ID
#BSUB -q regular             # queue

module load intel
module load mkl

#run the executable
mpirun.lsf ./tmmmobi -me Ae -mi Ai -external_forcing -numtracers 24 \
-t0 200.0 -iter0 144000 -deltat_clock 0.0013888888888889 -max_steps 144000 -write_steps 36000 \
-append \
-periodic_matrix -matrix_cycle_period 1.0 -matrix_cycle_step 0.0833333333333333 \
-periodic_biogeochem_forcing -periodic_biogeochem_cycle_period 1.0 -periodic_biogeochem_cycle_step 0.0833333333333333 \
-o v1out.petsc,v2out.petsc,v3out.petsc,v4out.petsc,v5out.petsc,v6out.petsc,v7out.petsc,v8out.petsc,v9out.petsc,v10out.petsc,v11out.petsc,v12out.petsc,v13out.petsc,v14out.petsc,v15out.petsc,v16out.petsc,v17out.petsc,v18out.petsc,v19out.petsc,v20out.petsc,v21out.petsc,v22out.petsc,v23out.petsc,v24out.petsc \
-nzmax 23 -biogeochem_deltat 43200.0 -use_profiles -use_emp \
-pickup pickup.petsc \
> log1
